import Head from 'next/head'
import Image from 'next/image'
import Logo from '../public/logo.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Andrey Agassi Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-white px-10'>
        <section className=' min-h-screen'>
          <nav className=' py-10 mb-12 flex justify-between md:px-10 lg:px-20'>
            <Image src={Logo} width="50px" height="50px" />
            <ul className=' flex items-center px-5 font-poppins md:px-10 lg:px-20'>
              <li><a className=' px-5 ' href='https://www.linkedin.com/in/andrey-agassi'>LinkedIn</a></li>
              <li><a className=' px-5 ' href='#'>Resume</a></li>
            </ul>
          </nav>
          <div>

          </div>
        </section>
      </main>
    </div>
  )
}
